### ISSUE TITLE
Error image file while creating XLSX file

### ISSUE THREAD

**Issue by RicGB** [SeryioGonzalez/azure-pricer#2]
/home/ricard/.local/lib/python3.6/site-packages/xlsxwriter/worksheet.py:1057: UserWarning: Image file '/home/sergio/test/azure-pricer/media/slide.jpg' not found.
  warn("Image file '%s' not found." % force_unicode(filename))

Parece que esta hardcodeado la posición del slide.jpg

Error menor

**Comment by SeryioGonzalez** [comment]
You need excel2016
