### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by atpatat** [SeryioGonzalez/azure-pricer#6]
Hi,

Running on Ubuntu. Getting this error when generating new file. Please assist? (Great tool!)

Traceback (most recent call last):
  File "xls_generator.py", line 8, in <module>
    from xlsStructure import xlsStructure as xls
  File "/azure-pricer-master/xlsStructure.py", line 68
    'validationList' : '=$' + alphabet[regionListColumn] + '$1:$' + alphabet[regionListColumn] + '$36'
                     ^
SyntaxError: invalid syntax

**Comment by SeryioGonzalez** [comment]
Hi @atpatat 

You need to provide a filename for the output. Are you doing this? See my execution. What I do is using an external bash script for coming up with a daily name

python3 /home/sergio/azure-pricer/xls_generator.py /home/sergio/azure-pricer/output/Azure-Quote-Tool-20210218.xlsx

**Comment by atpatat** [comment]
Hi Seryio,

Thanks for the advice. I find your Calculator extremely helpful and made
some modifications.

Can you perhaps advise what I need to change to bring in the BYOL costs for
Compute rather than VM costs with license included?

Many thanks,
Adriaan
