### ISSUE TITLE
Premium Storage calculation seems wrong

### ISSUE THREAD

**Issue by Zenocolo** [SeryioGonzalez/azure-pricer#7]
Hey Seryio,

First of all, love the tool! Calculating currently 3000 VM's, such a help, many thanks!
By reviewing the calculation I got the impression that premium storage calculations seemed bit low, after a closer look in the code resp. pricing API I think I found an error:

When searching for p-disk prices python script randomly caught mount prices (premiumssd-p20-disk-mount) for shared disks which are very low. (around 4$)

I fixed the code locally by filtering "and not 'disk-mount' in diskName" in the priceReaderManagedDisk.py file:

`		regionSizes  = {region + "-" + str(data['size']) : {'price':data['prices'][region]['value'], 'name':diskName.upper().split("-")[1], 'region':region, 'size':data['size']} for (diskName,data) in dataBasePrice['offers'].items() if keyWord in diskName and region in data['prices'] and not 'disk-mount' in diskName}`

Hope that helps, thanks again for the great tool!

Regards,
Philippe

**Comment by SeryioGonzalez** [comment]
Thanks Philippe

MultiVM mount was not available when I created the tool, so thanks for the pointer. Will fix it :)
Regards

Sergio
